// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcWpJdgIwoFK4QQ-QaQOmwc7Z41t3BNcY',
    appId: '1:975259947736:web:3bd8210f0e904a896b7dad',
    messagingSenderId: '975259947736',
    projectId: 'bookingapp-699dc',
    authDomain: 'bookingapp-699dc.firebaseapp.com',
    storageBucket: 'bookingapp-699dc.appspot.com',
    measurementId: 'G-VZDSFZB480',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3akuVx6k1obtnW2MRbFcQ4L-TS6QglXE',
    appId: '1:975259947736:android:41bdf15a17b0f9eb6b7dad',
    messagingSenderId: '975259947736',
    projectId: 'bookingapp-699dc',
    storageBucket: 'bookingapp-699dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdug83VB0Oq-mG9ZNJr5mSsndzj3llWX4',
    appId: '1:975259947736:ios:c420411253191fa06b7dad',
    messagingSenderId: '975259947736',
    projectId: 'bookingapp-699dc',
    storageBucket: 'bookingapp-699dc.appspot.com',
    iosClientId: '975259947736-psuhmnj0cfnrphbegrle2ptg22bp5ek8.apps.googleusercontent.com',
    iosBundleId: 'com.example.realestate',
  );
}
